package com.example.wuzp.secondworld.view.VarDb.greenDao.auto;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.wuzp.secondworld.view.VarDb.greenDao.ReaderBean;
import com.example.wuzp.secondworld.view.VarDb.greenDao.WriterBean;

import com.example.wuzp.secondworld.view.VarDb.greenDao.auto.ReaderBeanDao;
import com.example.wuzp.secondworld.view.VarDb.greenDao.auto.WriterBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig readerBeanDaoConfig;
    private final DaoConfig writerBeanDaoConfig;

    private final ReaderBeanDao readerBeanDao;
    private final WriterBeanDao writerBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        readerBeanDaoConfig = daoConfigMap.get(ReaderBeanDao.class).clone();
        readerBeanDaoConfig.initIdentityScope(type);

        writerBeanDaoConfig = daoConfigMap.get(WriterBeanDao.class).clone();
        writerBeanDaoConfig.initIdentityScope(type);

        readerBeanDao = new ReaderBeanDao(readerBeanDaoConfig, this);
        writerBeanDao = new WriterBeanDao(writerBeanDaoConfig, this);

        registerDao(ReaderBean.class, readerBeanDao);
        registerDao(WriterBean.class, writerBeanDao);
    }
    
    public void clear() {
        readerBeanDaoConfig.clearIdentityScope();
        writerBeanDaoConfig.clearIdentityScope();
    }

    public ReaderBeanDao getReaderBeanDao() {
        return readerBeanDao;
    }

    public WriterBeanDao getWriterBeanDao() {
        return writerBeanDao;
    }

}
